trigger:
  batch: true
  branches:
    exclude:
    - release/*
    - develop

resources:
  repositories:
    - repository: templates
      type: git
      name: ado-templates

parameters:
- name: testcases
  type: object
  default:
    # TODO: Add test case subfolder names
    - 01_example_testcase

extends:
  template: /stages/mainstage.yaml@templates
  parameters:
    wrap:
      testcases: ${{ parameters.testcases }}
